version: "2"

linters:
  enable:
    - bodyclose
    - err113
    - errorlint
    - fatcontext
    - gocritic
    - gosec
    - misspell
    - modernize
    - nilerr
    - noctx
    - sloglint

formatters:
  enable:
    - gofumpt
